# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/forms/qt\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuZoom = QtWidgets.QMenu(self.menuView)
        self.menuZoom.setObjectName("menuZoom")
        self.menuFlip_Rotate = QtWidgets.QMenu(self.menuView)
        self.menuFlip_Rotate.setObjectName("menuFlip_Rotate")
        self.menuScale = QtWidgets.QMenu(self.menuView)
        self.menuScale.setObjectName("menuScale")
        self.menuColor_Space = QtWidgets.QMenu(self.menuView)
        self.menuColor_Space.setObjectName("menuColor_Space")
        self.menuColorspace_Settings = QtWidgets.QMenu(self.menuColor_Space)
        self.menuColorspace_Settings.setObjectName("menuColorspace_Settings")
        self.menuTool_Windows = QtWidgets.QMenu(self.menuView)
        self.menuTool_Windows.setObjectName("menuTool_Windows")
        self.menuFrames = QtWidgets.QMenu(self.menuView)
        self.menuFrames.setObjectName("menuFrames")
        self.menuProcess = QtWidgets.QMenu(self.menubar)
        self.menuProcess.setObjectName("menuProcess")
        self.menuNoise_Removal = QtWidgets.QMenu(self.menuProcess)
        self.menuNoise_Removal.setObjectName("menuNoise_Removal")
        self.menuBad_Pixel_Removal = QtWidgets.QMenu(self.menuProcess)
        self.menuBad_Pixel_Removal.setObjectName("menuBad_Pixel_Removal")
        self.menuIgnore_Regions = QtWidgets.QMenu(self.menuProcess)
        self.menuIgnore_Regions.setObjectName("menuIgnore_Regions")
        self.menuRegions_of_Interest = QtWidgets.QMenu(self.menuProcess)
        self.menuRegions_of_Interest.setObjectName("menuRegions_of_Interest")
        self.menuScaling = QtWidgets.QMenu(self.menuProcess)
        self.menuScaling.setObjectName("menuScaling")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuSpectrum_Matching = QtWidgets.QMenu(self.menuAnalysis)
        self.menuSpectrum_Matching.setObjectName("menuSpectrum_Matching")
        self.menuMean_Values = QtWidgets.QMenu(self.menuAnalysis)
        self.menuMean_Values.setObjectName("menuMean_Values")
        self.menuMedian_Values = QtWidgets.QMenu(self.menuAnalysis)
        self.menuMedian_Values.setObjectName("menuMedian_Values")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFITS = QtWidgets.QMenu(self.menubar)
        self.menuFITS.setObjectName("menuFITS")
        self.menuExport = QtWidgets.QMenu(self.menuFITS)
        self.menuExport.setObjectName("menuExport")
        self.menuHeaders = QtWidgets.QMenu(self.menuFITS)
        self.menuHeaders.setObjectName("menuHeaders")
        self.menuTransform = QtWidgets.QMenu(self.menuFITS)
        self.menuTransform.setObjectName("menuTransform")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionSave_Project_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Project_As.setObjectName("actionSave_Project_As")
        self.actionClose_Project = QtWidgets.QAction(MainWindow)
        self.actionClose_Project.setObjectName("actionClose_Project")
        self.actionOpen_Settings = QtWidgets.QAction(MainWindow)
        self.actionOpen_Settings.setObjectName("actionOpen_Settings")
        self.actionImport_Settings = QtWidgets.QAction(MainWindow)
        self.actionImport_Settings.setObjectName("actionImport_Settings")
        self.actionExport_Settings = QtWidgets.QAction(MainWindow)
        self.actionExport_Settings.setObjectName("actionExport_Settings")
        self.actionExit_Program = QtWidgets.QAction(MainWindow)
        self.actionExit_Program.setObjectName("actionExit_Program")
        self.actionNew_FITS = QtWidgets.QAction(MainWindow)
        self.actionNew_FITS.setObjectName("actionNew_FITS")
        self.actionFITS_Open = QtWidgets.QAction(MainWindow)
        self.actionFITS_Open.setObjectName("actionFITS_Open")
        self.actionFITS_Save = QtWidgets.QAction(MainWindow)
        self.actionFITS_Save.setObjectName("actionFITS_Save")
        self.actionFITS_SaveAs = QtWidgets.QAction(MainWindow)
        self.actionFITS_SaveAs.setObjectName("actionFITS_SaveAs")
        self.actionas_PNG = QtWidgets.QAction(MainWindow)
        self.actionas_PNG.setObjectName("actionas_PNG")
        self.actionExportPNG = QtWidgets.QAction(MainWindow)
        self.actionExportPNG.setObjectName("actionExportPNG")
        self.actionExportJPG = QtWidgets.QAction(MainWindow)
        self.actionExportJPG.setObjectName("actionExportJPG")
        self.actionExportGIF = QtWidgets.QAction(MainWindow)
        self.actionExportGIF.setObjectName("actionExportGIF")
        self.actionNR_MedComb = QtWidgets.QAction(MainWindow)
        self.actionNR_MedComb.setObjectName("actionNR_MedComb")
        self.actionNR_NormMedComb = QtWidgets.QAction(MainWindow)
        self.actionNR_NormMedComb.setObjectName("actionNR_NormMedComb")
        self.actionBP_Manual_Removal = QtWidgets.QAction(MainWindow)
        self.actionBP_Manual_Removal.setObjectName("actionBP_Manual_Removal")
        self.actionBP_Threshold_Removal = QtWidgets.QAction(MainWindow)
        self.actionBP_Threshold_Removal.setObjectName("actionBP_Threshold_Removal")
        self.actionBP_Outlier_Removal = QtWidgets.QAction(MainWindow)
        self.actionBP_Outlier_Removal.setObjectName("actionBP_Outlier_Removal")
        self.actionAddIgnoreRegion = QtWidgets.QAction(MainWindow)
        self.actionAddIgnoreRegion.setObjectName("actionAddIgnoreRegion")
        self.actionDeleteIgnoreRegion = QtWidgets.QAction(MainWindow)
        self.actionDeleteIgnoreRegion.setObjectName("actionDeleteIgnoreRegion")
        self.actionNR_ManBackground = QtWidgets.QAction(MainWindow)
        self.actionNR_ManBackground.setObjectName("actionNR_ManBackground")
        self.actionEdit_Headers = QtWidgets.QAction(MainWindow)
        self.actionEdit_Headers.setObjectName("actionEdit_Headers")
        self.actionAddInterestRegion = QtWidgets.QAction(MainWindow)
        self.actionAddInterestRegion.setObjectName("actionAddInterestRegion")
        self.actionDeleteInterestRegion = QtWidgets.QAction(MainWindow)
        self.actionDeleteInterestRegion.setObjectName("actionDeleteInterestRegion")
        self.actionSpectrum_Automatic = QtWidgets.QAction(MainWindow)
        self.actionSpectrum_Automatic.setObjectName("actionSpectrum_Automatic")
        self.actionSpectrum_Manual = QtWidgets.QAction(MainWindow)
        self.actionSpectrum_Manual.setObjectName("actionSpectrum_Manual")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionGetting_Started = QtWidgets.QAction(MainWindow)
        self.actionGetting_Started.setObjectName("actionGetting_Started")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSubmit_Bug_Report_Feedback = QtWidgets.QAction(MainWindow)
        self.actionSubmit_Bug_Report_Feedback.setObjectName("actionSubmit_Bug_Report_Feedback")
        self.actionFITS_Close = QtWidgets.QAction(MainWindow)
        self.actionFITS_Close.setObjectName("actionFITS_Close")
        self.actionHeaders_View = QtWidgets.QAction(MainWindow)
        self.actionHeaders_View.setObjectName("actionHeaders_View")
        self.actionHeaders_Edit = QtWidgets.QAction(MainWindow)
        self.actionHeaders_Edit.setObjectName("actionHeaders_Edit")
        self.actionUndo_Edit = QtWidgets.QAction(MainWindow)
        self.actionUndo_Edit.setObjectName("actionUndo_Edit")
        self.actionRedo_Edit = QtWidgets.QAction(MainWindow)
        self.actionRedo_Edit.setObjectName("actionRedo_Edit")
        self.actionRevert_Changes = QtWidgets.QAction(MainWindow)
        self.actionRevert_Changes.setObjectName("actionRevert_Changes")
        self.actionEditCut_File = QtWidgets.QAction(MainWindow)
        self.actionEditCut_File.setObjectName("actionEditCut_File")
        self.actionEditCopy_File = QtWidgets.QAction(MainWindow)
        self.actionEditCopy_File.setObjectName("actionEditCopy_File")
        self.actionEditPaste_File = QtWidgets.QAction(MainWindow)
        self.actionEditPaste_File.setObjectName("actionEditPaste_File")
        self.actionEditDelete = QtWidgets.QAction(MainWindow)
        self.actionEditDelete.setObjectName("actionEditDelete")
        self.actionRename_File = QtWidgets.QAction(MainWindow)
        self.actionRename_File.setObjectName("actionRename_File")
        self.actionViewCenterImage = QtWidgets.QAction(MainWindow)
        self.actionViewCenterImage.setObjectName("actionViewCenterImage")
        self.actionViewFullscreen = QtWidgets.QAction(MainWindow)
        self.actionViewFullscreen.setObjectName("actionViewFullscreen")
        self.actionResetView_Zoom = QtWidgets.QAction(MainWindow)
        self.actionResetView_Zoom.setObjectName("actionResetView_Zoom")
        self.actionViewZoomIn = QtWidgets.QAction(MainWindow)
        self.actionViewZoomIn.setObjectName("actionViewZoomIn")
        self.actionViewZoomOut = QtWidgets.QAction(MainWindow)
        self.actionViewZoomOut.setObjectName("actionViewZoomOut")
        self.actionViewZoomToSelection = QtWidgets.QAction(MainWindow)
        self.actionViewZoomToSelection.setObjectName("actionViewZoomToSelection")
        self.actionViewCenterSelection = QtWidgets.QAction(MainWindow)
        self.actionViewCenterSelection.setObjectName("actionViewCenterSelection")
        self.actionViewFit_to_Window = QtWidgets.QAction(MainWindow)
        self.actionViewFit_to_Window.setObjectName("actionViewFit_to_Window")
        self.actionViewZoom1600 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom1600.setObjectName("actionViewZoom1600")
        self.actionViewZoom800 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom800.setObjectName("actionViewZoom800")
        self.actionViewZoom400 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom400.setObjectName("actionViewZoom400")
        self.actionViewZoom200 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom200.setObjectName("actionViewZoom200")
        self.actionViewZoom100 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom100.setObjectName("actionViewZoom100")
        self.actionViewZoom50 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom50.setObjectName("actionViewZoom50")
        self.actionViewZoom25 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom25.setObjectName("actionViewZoom25")
        self.actionViewZoom12 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom12.setObjectName("actionViewZoom12")
        self.actionViewZoom6 = QtWidgets.QAction(MainWindow)
        self.actionViewZoom6.setObjectName("actionViewZoom6")
        self.actionViewCustomZoom = QtWidgets.QAction(MainWindow)
        self.actionViewCustomZoom.setObjectName("actionViewCustomZoom")
        self.actionResetViewFlipRotate = QtWidgets.QAction(MainWindow)
        self.actionResetViewFlipRotate.setObjectName("actionResetViewFlipRotate")
        self.actionViewFlip_Horizontal = QtWidgets.QAction(MainWindow)
        self.actionViewFlip_Horizontal.setObjectName("actionViewFlip_Horizontal")
        self.actionViewFlip_Vertical = QtWidgets.QAction(MainWindow)
        self.actionViewFlip_Vertical.setObjectName("actionViewFlip_Vertical")
        self.actionViewRotate_15_CW = QtWidgets.QAction(MainWindow)
        self.actionViewRotate_15_CW.setObjectName("actionViewRotate_15_CW")
        self.actionViewRotate_15_CCW = QtWidgets.QAction(MainWindow)
        self.actionViewRotate_15_CCW.setObjectName("actionViewRotate_15_CCW")
        self.actionViewRotate_90_CW = QtWidgets.QAction(MainWindow)
        self.actionViewRotate_90_CW.setObjectName("actionViewRotate_90_CW")
        self.actionViewRotate_90_CCW = QtWidgets.QAction(MainWindow)
        self.actionViewRotate_90_CCW.setObjectName("actionViewRotate_90_CCW")
        self.actionViewRotate_180 = QtWidgets.QAction(MainWindow)
        self.actionViewRotate_180.setObjectName("actionViewRotate_180")
        self.actionViewOtherRotateAngle = QtWidgets.QAction(MainWindow)
        self.actionViewOtherRotateAngle.setObjectName("actionViewOtherRotateAngle")
        self.actionViewScaleLinear = QtWidgets.QAction(MainWindow)
        self.actionViewScaleLinear.setObjectName("actionViewScaleLinear")
        self.actionViewScaleLogarithmic = QtWidgets.QAction(MainWindow)
        self.actionViewScaleLogarithmic.setObjectName("actionViewScaleLogarithmic")
        self.actionViewScalePower = QtWidgets.QAction(MainWindow)
        self.actionViewScalePower.setObjectName("actionViewScalePower")
        self.actionViewScaleSquare_Root = QtWidgets.QAction(MainWindow)
        self.actionViewScaleSquare_Root.setObjectName("actionViewScaleSquare_Root")
        self.actionViewScaleSquared = QtWidgets.QAction(MainWindow)
        self.actionViewScaleSquared.setObjectName("actionViewScaleSquared")
        self.actionViewScaleasinh = QtWidgets.QAction(MainWindow)
        self.actionViewScaleasinh.setObjectName("actionViewScaleasinh")
        self.actionViewScalesinh = QtWidgets.QAction(MainWindow)
        self.actionViewScalesinh.setObjectName("actionViewScalesinh")
        self.actionViewScaleHistogram = QtWidgets.QAction(MainWindow)
        self.actionViewScaleHistogram.setObjectName("actionViewScaleHistogram")
        self.actionViewScaleMin_Max = QtWidgets.QAction(MainWindow)
        self.actionViewScaleMin_Max.setObjectName("actionViewScaleMin_Max")
        self.actionViewScaleZ_Scale = QtWidgets.QAction(MainWindow)
        self.actionViewScaleZ_Scale.setObjectName("actionViewScaleZ_Scale")
        self.actionSetColorGreyscale = QtWidgets.QAction(MainWindow)
        self.actionSetColorGreyscale.setObjectName("actionSetColorGreyscale")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionB = QtWidgets.QAction(MainWindow)
        self.actionB.setObjectName("actionB")
        self.actionSetColorBlack_Body = QtWidgets.QAction(MainWindow)
        self.actionSetColorBlack_Body.setObjectName("actionSetColorBlack_Body")
        self.actionSetColorHeatmap = QtWidgets.QAction(MainWindow)
        self.actionSetColorHeatmap.setObjectName("actionSetColorHeatmap")
        self.actioni8 = QtWidgets.QAction(MainWindow)
        self.actioni8.setObjectName("actioni8")
        self.actionaips0 = QtWidgets.QAction(MainWindow)
        self.actionaips0.setObjectName("actionaips0")
        self.actionSetColorCool = QtWidgets.QAction(MainWindow)
        self.actionSetColorCool.setObjectName("actionSetColorCool")
        self.actionSetColorRainbow = QtWidgets.QAction(MainWindow)
        self.actionSetColorRainbow.setObjectName("actionSetColorRainbow")
        self.actionColorspaceEdit = QtWidgets.QAction(MainWindow)
        self.actionColorspaceEdit.setObjectName("actionColorspaceEdit")
        self.actionColorspaceSave = QtWidgets.QAction(MainWindow)
        self.actionColorspaceSave.setObjectName("actionColorspaceSave")
        self.actionColorspaceLoad = QtWidgets.QAction(MainWindow)
        self.actionColorspaceLoad.setObjectName("actionColorspaceLoad")
        self.actionViewProject_Panel = QtWidgets.QAction(MainWindow)
        self.actionViewProject_Panel.setObjectName("actionViewProject_Panel")
        self.actionViewThumbnail = QtWidgets.QAction(MainWindow)
        self.actionViewThumbnail.setObjectName("actionViewThumbnail")
        self.actionViewMagnifier_View = QtWidgets.QAction(MainWindow)
        self.actionViewMagnifier_View.setObjectName("actionViewMagnifier_View")
        self.actionViewInfo_Panel = QtWidgets.QAction(MainWindow)
        self.actionViewInfo_Panel.setObjectName("actionViewInfo_Panel")
        self.actionViewColor_Map = QtWidgets.QAction(MainWindow)
        self.actionViewColor_Map.setObjectName("actionViewColor_Map")
        self.actionViewSingleFrames = QtWidgets.QAction(MainWindow)
        self.actionViewSingleFrames.setObjectName("actionViewSingleFrames")
        self.actionViewTiledFrames = QtWidgets.QAction(MainWindow)
        self.actionViewTiledFrames.setObjectName("actionViewTiledFrames")
        self.actionFITS_FlipHorizontal = QtWidgets.QAction(MainWindow)
        self.actionFITS_FlipHorizontal.setObjectName("actionFITS_FlipHorizontal")
        self.actionFITS_FlipVertical = QtWidgets.QAction(MainWindow)
        self.actionFITS_FlipVertical.setObjectName("actionFITS_FlipVertical")
        self.actionFITS_Rotate_90_CW = QtWidgets.QAction(MainWindow)
        self.actionFITS_Rotate_90_CW.setObjectName("actionFITS_Rotate_90_CW")
        self.actionFITS_Rotate_90_CCW = QtWidgets.QAction(MainWindow)
        self.actionFITS_Rotate_90_CCW.setObjectName("actionFITS_Rotate_90_CCW")
        self.actionFITS_Rotate_180 = QtWidgets.QAction(MainWindow)
        self.actionFITS_Rotate_180.setObjectName("actionFITS_Rotate_180")
        self.actionFITS_Crop_to_Selection = QtWidgets.QAction(MainWindow)
        self.actionFITS_Crop_to_Selection.setObjectName("actionFITS_Crop_to_Selection")
        self.actionViewTool_Box = QtWidgets.QAction(MainWindow)
        self.actionViewTool_Box.setObjectName("actionViewTool_Box")
        self.actionStripe_Scaling = QtWidgets.QAction(MainWindow)
        self.actionStripe_Scaling.setObjectName("actionStripe_Scaling")
        self.actionSpline_Interpolation = QtWidgets.QAction(MainWindow)
        self.actionSpline_Interpolation.setObjectName("actionSpline_Interpolation")
        self.actionScale_TileStripe = QtWidgets.QAction(MainWindow)
        self.actionScale_TileStripe.setObjectName("actionScale_TileStripe")
        self.actionScale_SplineTerp = QtWidgets.QAction(MainWindow)
        self.actionScale_SplineTerp.setObjectName("actionScale_SplineTerp")
        self.actionViewMeasurements = QtWidgets.QAction(MainWindow)
        self.actionViewMeasurements.setObjectName("actionViewMeasurements")
        self.actionMean_Horizontal = QtWidgets.QAction(MainWindow)
        self.actionMean_Horizontal.setObjectName("actionMean_Horizontal")
        self.actionMean_Vertical = QtWidgets.QAction(MainWindow)
        self.actionMean_Vertical.setObjectName("actionMean_Vertical")
        self.actionMean_Custom = QtWidgets.QAction(MainWindow)
        self.actionMean_Custom.setObjectName("actionMean_Custom")
        self.actionMedian_Horizontal = QtWidgets.QAction(MainWindow)
        self.actionMedian_Horizontal.setObjectName("actionMedian_Horizontal")
        self.actionMedian_Vertical = QtWidgets.QAction(MainWindow)
        self.actionMedian_Vertical.setObjectName("actionMedian_Vertical")
        self.actionMedian_Custom = QtWidgets.QAction(MainWindow)
        self.actionMedian_Custom.setObjectName("actionMedian_Custom")
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_Project_As)
        self.menuFile.addAction(self.actionClose_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Settings)
        self.menuFile.addAction(self.actionImport_Settings)
        self.menuFile.addAction(self.actionExport_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_Program)
        self.menuEdit.addAction(self.actionUndo_Edit)
        self.menuEdit.addAction(self.actionRedo_Edit)
        self.menuEdit.addAction(self.actionRevert_Changes)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEditCut_File)
        self.menuEdit.addAction(self.actionEditCopy_File)
        self.menuEdit.addAction(self.actionEditPaste_File)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRename_File)
        self.menuZoom.addAction(self.actionResetView_Zoom)
        self.menuZoom.addAction(self.actionViewZoomIn)
        self.menuZoom.addAction(self.actionViewZoomOut)
        self.menuZoom.addAction(self.actionViewZoomToSelection)
        self.menuZoom.addSeparator()
        self.menuZoom.addAction(self.actionViewFit_to_Window)
        self.menuZoom.addSeparator()
        self.menuZoom.addAction(self.actionViewZoom1600)
        self.menuZoom.addAction(self.actionViewZoom800)
        self.menuZoom.addAction(self.actionViewZoom400)
        self.menuZoom.addAction(self.actionViewZoom200)
        self.menuZoom.addAction(self.actionViewZoom100)
        self.menuZoom.addAction(self.actionViewZoom50)
        self.menuZoom.addAction(self.actionViewZoom25)
        self.menuZoom.addAction(self.actionViewZoom12)
        self.menuZoom.addAction(self.actionViewZoom6)
        self.menuZoom.addSeparator()
        self.menuZoom.addAction(self.actionViewCustomZoom)
        self.menuFlip_Rotate.addAction(self.actionResetViewFlipRotate)
        self.menuFlip_Rotate.addSeparator()
        self.menuFlip_Rotate.addAction(self.actionViewFlip_Horizontal)
        self.menuFlip_Rotate.addAction(self.actionViewFlip_Vertical)
        self.menuFlip_Rotate.addSeparator()
        self.menuFlip_Rotate.addAction(self.actionViewRotate_15_CW)
        self.menuFlip_Rotate.addAction(self.actionViewRotate_15_CCW)
        self.menuFlip_Rotate.addAction(self.actionViewRotate_90_CW)
        self.menuFlip_Rotate.addAction(self.actionViewRotate_90_CCW)
        self.menuFlip_Rotate.addAction(self.actionViewRotate_180)
        self.menuFlip_Rotate.addSeparator()
        self.menuFlip_Rotate.addAction(self.actionViewOtherRotateAngle)
        self.menuScale.addAction(self.actionViewScaleLinear)
        self.menuScale.addAction(self.actionViewScaleLogarithmic)
        self.menuScale.addAction(self.actionViewScalePower)
        self.menuScale.addAction(self.actionViewScaleSquare_Root)
        self.menuScale.addAction(self.actionViewScaleSquared)
        self.menuScale.addAction(self.actionViewScaleasinh)
        self.menuScale.addAction(self.actionViewScalesinh)
        self.menuScale.addAction(self.actionViewScaleHistogram)
        self.menuScale.addAction(self.actionViewScaleMin_Max)
        self.menuScale.addAction(self.actionViewScaleZ_Scale)
        self.menuColorspace_Settings.addAction(self.actionColorspaceEdit)
        self.menuColorspace_Settings.addAction(self.actionColorspaceSave)
        self.menuColorspace_Settings.addAction(self.actionColorspaceLoad)
        self.menuColor_Space.addAction(self.actionSetColorGreyscale)
        self.menuColor_Space.addAction(self.actionSetColorBlack_Body)
        self.menuColor_Space.addAction(self.actionSetColorHeatmap)
        self.menuColor_Space.addAction(self.actionSetColorCool)
        self.menuColor_Space.addAction(self.actionSetColorRainbow)
        self.menuColor_Space.addSeparator()
        self.menuColor_Space.addAction(self.menuColorspace_Settings.menuAction())
        self.menuTool_Windows.addAction(self.actionViewProject_Panel)
        self.menuTool_Windows.addAction(self.actionViewInfo_Panel)
        self.menuTool_Windows.addAction(self.actionViewThumbnail)
        self.menuTool_Windows.addAction(self.actionViewMagnifier_View)
        self.menuTool_Windows.addAction(self.actionViewColor_Map)
        self.menuTool_Windows.addAction(self.actionViewTool_Box)
        self.menuFrames.addAction(self.actionViewSingleFrames)
        self.menuFrames.addAction(self.actionViewTiledFrames)
        self.menuView.addAction(self.menuTool_Windows.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuFrames.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.menuFlip_Rotate.menuAction())
        self.menuView.addAction(self.actionViewCenterImage)
        self.menuView.addAction(self.actionViewCenterSelection)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionViewFullscreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuColor_Space.menuAction())
        self.menuView.addAction(self.menuScale.menuAction())
        self.menuNoise_Removal.addAction(self.actionNR_MedComb)
        self.menuNoise_Removal.addAction(self.actionNR_NormMedComb)
        self.menuNoise_Removal.addAction(self.actionNR_ManBackground)
        self.menuBad_Pixel_Removal.addAction(self.actionBP_Manual_Removal)
        self.menuBad_Pixel_Removal.addAction(self.actionBP_Threshold_Removal)
        self.menuBad_Pixel_Removal.addAction(self.actionBP_Outlier_Removal)
        self.menuIgnore_Regions.addAction(self.actionAddIgnoreRegion)
        self.menuIgnore_Regions.addAction(self.actionDeleteIgnoreRegion)
        self.menuRegions_of_Interest.addAction(self.actionAddInterestRegion)
        self.menuRegions_of_Interest.addAction(self.actionDeleteInterestRegion)
        self.menuScaling.addAction(self.actionScale_TileStripe)
        self.menuScaling.addAction(self.actionScale_SplineTerp)
        self.menuProcess.addAction(self.menuNoise_Removal.menuAction())
        self.menuProcess.addAction(self.menuBad_Pixel_Removal.menuAction())
        self.menuProcess.addAction(self.menuIgnore_Regions.menuAction())
        self.menuProcess.addAction(self.menuRegions_of_Interest.menuAction())
        self.menuProcess.addAction(self.menuScaling.menuAction())
        self.menuSpectrum_Matching.addAction(self.actionSpectrum_Automatic)
        self.menuSpectrum_Matching.addAction(self.actionSpectrum_Manual)
        self.menuMean_Values.addAction(self.actionMean_Horizontal)
        self.menuMean_Values.addAction(self.actionMean_Vertical)
        self.menuMean_Values.addSeparator()
        self.menuMean_Values.addAction(self.actionMean_Custom)
        self.menuMedian_Values.addAction(self.actionMedian_Horizontal)
        self.menuMedian_Values.addAction(self.actionMedian_Vertical)
        self.menuMedian_Values.addSeparator()
        self.menuMedian_Values.addAction(self.actionMedian_Custom)
        self.menuAnalysis.addAction(self.menuSpectrum_Matching.menuAction())
        self.menuAnalysis.addAction(self.actionViewMeasurements)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.menuMean_Values.menuAction())
        self.menuAnalysis.addAction(self.menuMedian_Values.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionGetting_Started)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionSubmit_Bug_Report_Feedback)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuExport.addAction(self.actionExportPNG)
        self.menuExport.addAction(self.actionExportJPG)
        self.menuExport.addAction(self.actionExportGIF)
        self.menuHeaders.addAction(self.actionHeaders_View)
        self.menuHeaders.addAction(self.actionHeaders_Edit)
        self.menuTransform.addAction(self.actionFITS_FlipHorizontal)
        self.menuTransform.addAction(self.actionFITS_FlipVertical)
        self.menuTransform.addSeparator()
        self.menuTransform.addAction(self.actionFITS_Rotate_90_CW)
        self.menuTransform.addAction(self.actionFITS_Rotate_90_CCW)
        self.menuTransform.addAction(self.actionFITS_Rotate_180)
        self.menuFITS.addAction(self.actionNew_FITS)
        self.menuFITS.addAction(self.actionFITS_Open)
        self.menuFITS.addAction(self.actionFITS_Save)
        self.menuFITS.addAction(self.actionFITS_SaveAs)
        self.menuFITS.addAction(self.menuExport.menuAction())
        self.menuFITS.addSeparator()
        self.menuFITS.addAction(self.menuTransform.menuAction())
        self.menuFITS.addAction(self.actionFITS_Crop_to_Selection)
        self.menuFITS.addSeparator()
        self.menuFITS.addAction(self.menuHeaders.menuAction())
        self.menuFITS.addSeparator()
        self.menuFITS.addAction(self.actionFITS_Close)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFITS.menuAction())
        self.menubar.addAction(self.menuProcess.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual FITS Analyzer"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuZoom.setTitle(_translate("MainWindow", "Zoom"))
        self.menuFlip_Rotate.setTitle(_translate("MainWindow", "Flip / Rotate"))
        self.menuScale.setTitle(_translate("MainWindow", "Scale"))
        self.menuColor_Space.setTitle(_translate("MainWindow", "Color Space"))
        self.menuColorspace_Settings.setTitle(_translate("MainWindow", "Colorspace Settings..."))
        self.menuTool_Windows.setTitle(_translate("MainWindow", "Tool Windows"))
        self.menuFrames.setTitle(_translate("MainWindow", "Frames"))
        self.menuProcess.setTitle(_translate("MainWindow", "Process"))
        self.menuNoise_Removal.setTitle(_translate("MainWindow", "Noise Removal..."))
        self.menuBad_Pixel_Removal.setTitle(_translate("MainWindow", "Bad Pixels..."))
        self.menuIgnore_Regions.setTitle(_translate("MainWindow", "Ignore Regions..."))
        self.menuRegions_of_Interest.setTitle(_translate("MainWindow", "Regions of Interest..."))
        self.menuScaling.setTitle(_translate("MainWindow", "Scaling"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuSpectrum_Matching.setTitle(_translate("MainWindow", "Spectral Line Matching"))
        self.menuMean_Values.setTitle(_translate("MainWindow", "Mean Values"))
        self.menuMedian_Values.setTitle(_translate("MainWindow", "Median Values"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFITS.setTitle(_translate("MainWindow", "FITS"))
        self.menuExport.setTitle(_translate("MainWindow", "Export As..."))
        self.menuHeaders.setTitle(_translate("MainWindow", "Headers..."))
        self.menuTransform.setTitle(_translate("MainWindow", "Transform"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionSave_Project_As.setText(_translate("MainWindow", "Save Project As"))
        self.actionClose_Project.setText(_translate("MainWindow", "Close Project"))
        self.actionOpen_Settings.setText(_translate("MainWindow", "Settings..."))
        self.actionImport_Settings.setText(_translate("MainWindow", "Import Settings"))
        self.actionExport_Settings.setText(_translate("MainWindow", "Export Settings"))
        self.actionExit_Program.setText(_translate("MainWindow", "Exit"))
        self.actionNew_FITS.setText(_translate("MainWindow", "New..."))
        self.actionFITS_Open.setText(_translate("MainWindow", "Open..."))
        self.actionFITS_Save.setText(_translate("MainWindow", "Save"))
        self.actionFITS_SaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionas_PNG.setText(_translate("MainWindow", "as PNG"))
        self.actionExportPNG.setText(_translate("MainWindow", "PNG"))
        self.actionExportJPG.setText(_translate("MainWindow", "JPG"))
        self.actionExportGIF.setText(_translate("MainWindow", "GIF"))
        self.actionNR_MedComb.setText(_translate("MainWindow", "Median Combination"))
        self.actionNR_NormMedComb.setText(_translate("MainWindow", "Norm. Median Combination"))
        self.actionBP_Manual_Removal.setText(_translate("MainWindow", "Manual Removal"))
        self.actionBP_Threshold_Removal.setText(_translate("MainWindow", "Threshold Removal"))
        self.actionBP_Outlier_Removal.setText(_translate("MainWindow", "Outlier Removal"))
        self.actionAddIgnoreRegion.setText(_translate("MainWindow", "Add Region"))
        self.actionDeleteIgnoreRegion.setText(_translate("MainWindow", "Delete Region"))
        self.actionNR_ManBackground.setText(_translate("MainWindow", "Manual Background Removal"))
        self.actionEdit_Headers.setText(_translate("MainWindow", "Edit Headers"))
        self.actionAddInterestRegion.setText(_translate("MainWindow", "Add Region"))
        self.actionDeleteInterestRegion.setText(_translate("MainWindow", "Delete Region"))
        self.actionSpectrum_Automatic.setText(_translate("MainWindow", "Automatic"))
        self.actionSpectrum_Manual.setText(_translate("MainWindow", "Manual"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionGetting_Started.setText(_translate("MainWindow", "Getting Started"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionSubmit_Bug_Report_Feedback.setText(_translate("MainWindow", "Submit Bug Report/Feedback..."))
        self.actionFITS_Close.setText(_translate("MainWindow", "Close File"))
        self.actionHeaders_View.setText(_translate("MainWindow", "View"))
        self.actionHeaders_Edit.setText(_translate("MainWindow", "Edit"))
        self.actionUndo_Edit.setText(_translate("MainWindow", "Undo"))
        self.actionRedo_Edit.setText(_translate("MainWindow", "Redo"))
        self.actionRevert_Changes.setText(_translate("MainWindow", "Revert Changes"))
        self.actionEditCut_File.setText(_translate("MainWindow", "Cut"))
        self.actionEditCopy_File.setText(_translate("MainWindow", "Copy"))
        self.actionEditPaste_File.setText(_translate("MainWindow", "Paste"))
        self.actionEditDelete.setText(_translate("MainWindow", "Delete"))
        self.actionRename_File.setText(_translate("MainWindow", "Rename"))
        self.actionViewCenterImage.setText(_translate("MainWindow", "Center Image in Window"))
        self.actionViewFullscreen.setText(_translate("MainWindow", "Fullscreen"))
        self.actionResetView_Zoom.setText(_translate("MainWindow", "Reset Zoom"))
        self.actionViewZoomIn.setText(_translate("MainWindow", "Zoom +"))
        self.actionViewZoomOut.setText(_translate("MainWindow", "Zoom -"))
        self.actionViewZoomToSelection.setText(_translate("MainWindow", "Zoom on Selection"))
        self.actionViewCenterSelection.setText(_translate("MainWindow", "Center Selection in Window"))
        self.actionViewFit_to_Window.setText(_translate("MainWindow", "Fit to Window"))
        self.actionViewZoom1600.setText(_translate("MainWindow", "16:1 (1600%)"))
        self.actionViewZoom800.setText(_translate("MainWindow", "8:1 (800%)"))
        self.actionViewZoom400.setText(_translate("MainWindow", "4:1 (400%)"))
        self.actionViewZoom200.setText(_translate("MainWindow", "2:1 (200%)"))
        self.actionViewZoom100.setText(_translate("MainWindow", "1:1 (100%)"))
        self.actionViewZoom50.setText(_translate("MainWindow", "1:2 (50%)"))
        self.actionViewZoom25.setText(_translate("MainWindow", "1:4 (25%)"))
        self.actionViewZoom12.setText(_translate("MainWindow", "1:8 (12.5%)"))
        self.actionViewZoom6.setText(_translate("MainWindow", "1:16 (6.25%)"))
        self.actionViewCustomZoom.setText(_translate("MainWindow", "Custom Zoom Factor..."))
        self.actionResetViewFlipRotate.setText(_translate("MainWindow", "Reset Flip / Rotate"))
        self.actionViewFlip_Horizontal.setText(_translate("MainWindow", "Flip Horizontal"))
        self.actionViewFlip_Vertical.setText(_translate("MainWindow", "Flip Vertical"))
        self.actionViewRotate_15_CW.setText(_translate("MainWindow", "Rotate 15° CW"))
        self.actionViewRotate_15_CCW.setText(_translate("MainWindow", "Rotate 15° CCW"))
        self.actionViewRotate_90_CW.setText(_translate("MainWindow", "Rotate 90° CW"))
        self.actionViewRotate_90_CCW.setText(_translate("MainWindow", "Rotate 90° CCW"))
        self.actionViewRotate_180.setText(_translate("MainWindow", "Rotate 180°"))
        self.actionViewOtherRotateAngle.setText(_translate("MainWindow", "Other Rotation Angle..."))
        self.actionViewScaleLinear.setText(_translate("MainWindow", "Linear"))
        self.actionViewScaleLogarithmic.setText(_translate("MainWindow", "Logarithmic"))
        self.actionViewScalePower.setText(_translate("MainWindow", "Power"))
        self.actionViewScaleSquare_Root.setText(_translate("MainWindow", "Square Root"))
        self.actionViewScaleSquared.setText(_translate("MainWindow", "Squared"))
        self.actionViewScaleasinh.setText(_translate("MainWindow", "asinh"))
        self.actionViewScalesinh.setText(_translate("MainWindow", "sinh"))
        self.actionViewScaleHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionViewScaleMin_Max.setText(_translate("MainWindow", "Min/Max"))
        self.actionViewScaleZ_Scale.setText(_translate("MainWindow", "Z-Scale"))
        self.actionSetColorGreyscale.setText(_translate("MainWindow", "Greyscale"))
        self.actionA.setText(_translate("MainWindow", "A"))
        self.actionB.setText(_translate("MainWindow", "B"))
        self.actionSetColorBlack_Body.setText(_translate("MainWindow", "Black Body"))
        self.actionSetColorHeatmap.setText(_translate("MainWindow", "Heat"))
        self.actioni8.setText(_translate("MainWindow", "i8"))
        self.actionaips0.setText(_translate("MainWindow", "aips0"))
        self.actionSetColorCool.setText(_translate("MainWindow", "Cool"))
        self.actionSetColorRainbow.setText(_translate("MainWindow", "Rainbow"))
        self.actionColorspaceEdit.setText(_translate("MainWindow", "Edit"))
        self.actionColorspaceSave.setText(_translate("MainWindow", "Save"))
        self.actionColorspaceLoad.setText(_translate("MainWindow", "Load..."))
        self.actionViewProject_Panel.setText(_translate("MainWindow", "Project Panel"))
        self.actionViewThumbnail.setText(_translate("MainWindow", "Thumbnail"))
        self.actionViewMagnifier_View.setText(_translate("MainWindow", "Magnifier View"))
        self.actionViewInfo_Panel.setText(_translate("MainWindow", "Info Panel"))
        self.actionViewColor_Map.setText(_translate("MainWindow", "Color Map"))
        self.actionViewSingleFrames.setText(_translate("MainWindow", "Single"))
        self.actionViewTiledFrames.setText(_translate("MainWindow", "Tiled"))
        self.actionFITS_FlipHorizontal.setText(_translate("MainWindow", "Flip Horizontal"))
        self.actionFITS_FlipVertical.setText(_translate("MainWindow", "Flip Vertical"))
        self.actionFITS_Rotate_90_CW.setText(_translate("MainWindow", "Rotate 90° CW"))
        self.actionFITS_Rotate_90_CCW.setText(_translate("MainWindow", "Rotate 90° CCW"))
        self.actionFITS_Rotate_180.setText(_translate("MainWindow", "Rotate 180°"))
        self.actionFITS_Crop_to_Selection.setText(_translate("MainWindow", "Crop to Selection"))
        self.actionViewTool_Box.setText(_translate("MainWindow", "Tool Box"))
        self.actionStripe_Scaling.setText(_translate("MainWindow", "Tile/Stripe Scaling..."))
        self.actionSpline_Interpolation.setText(_translate("MainWindow", "Spline Interpolation"))
        self.actionScale_TileStripe.setText(_translate("MainWindow", "Tile / Stripe"))
        self.actionScale_SplineTerp.setText(_translate("MainWindow", "Spline Interpolation"))
        self.actionViewMeasurements.setText(_translate("MainWindow", "Measurements"))
        self.actionMean_Horizontal.setText(_translate("MainWindow", "Horizontal"))
        self.actionMean_Vertical.setText(_translate("MainWindow", "Vertical"))
        self.actionMean_Custom.setText(_translate("MainWindow", "Custom Region"))
        self.actionMedian_Horizontal.setText(_translate("MainWindow", "Horizontal"))
        self.actionMedian_Vertical.setText(_translate("MainWindow", "Vertical"))
        self.actionMedian_Custom.setText(_translate("MainWindow", "Custom Region"))
